### PR TITLE
Add profile for Showtec Compact PAR 7 Q4.

### PR DESCRIPTION
**Pull request by lndr**

### CODE REVIEW

**Comment by lndr** [comment]
Thanks for the advice. I must have overlooked that one when I checked for the implementation of fixtures with multiple modes. I updated the profile accordingly and also added virtual dimmers to the four-channel version. All work as expected with my hardware.

Best regards.

**Comment by lndr** [comment]
I could add a generic interface with mode as a parameter, however, I'd realize it using a function. The outside behaviour would be identical but one would avoid turning one object into another by replacing __ dict __, e.g.:

```
def Compact_PAR_7_Q4(mode, *args, **kwargs):
    if mode == 4:
        return Compact_PAR_7_Q4_4Ch(*args, **kwargs)
    elif mode == 6:
        return Compact_PAR_7_Q4_6Ch(*args, **kwargs)
    elif mode == 11:
        return Compact_PAR_7_Q4_11Ch(*args, **kwargs)
    else:
        raise ValueError('Number of channels (mode) has to be 4, 6, or 11. You passed '
                         '{}.'.format(mode))

```

**Comment by MattIPv4** [comment]
Using a mutating class allows for fixture profile selection to work correctly, otherwise I would've used a function initially:

```python
from PyDMXControl.controllers import Controller
from PyDMXControl.profiles.Stairville import Quad_Par_Profile

dmx = Controller()

# Fixtures
dmx.add_fixture(Quad_Par_Profile, mode=4)
dmx.add_fixture(Quad_Par_Profile, mode=6)
dmx.add_fixture(Quad_Par_Profile, mode=8)

# Test profile selection
print(dmx.get_fixtures_by_profile(Quad_Par_Profile))
```

```
[<PyDMXControl.profiles.Stairville._Quad_Par_Profile.Quad_Par_Profile object at 0x10fb57e80>, <PyDMXControl.profiles.Stairville._Quad_Par_Profile.Quad_Par_Profile object at 0x10fb57eb8>, <PyDMXControl.profiles.Stairville._Quad_Par_Profile.Quad_Par_Profile object at 0x10fb7e1d0>]
```

**Comment by lndr** [comment]
I added the generic class you requested.

**Comment by MattIPv4** [comment]
:shipit:

**Comment by MattIPv4** [comment]
Tyvm for this!

**Pull request merged**
